// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX5HcULBvBPzflB5jvsxqsp8chJpSYU1c',
    appId: '1:808372705014:web:794da92680c98c2bc1bed7',
    messagingSenderId: '808372705014',
    projectId: 'meeting-module-4959e',
    authDomain: 'meeting-module-4959e.firebaseapp.com',
    databaseURL: 'https://meeting-module-4959e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'meeting-module-4959e.appspot.com',
    measurementId: 'G-5P587B10DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgnqE0erpdE9-AHD6YtGgwQeNuiT62CFc',
    appId: '1:808372705014:android:8c7376135d66f720c1bed7',
    messagingSenderId: '808372705014',
    projectId: 'meeting-module-4959e',
    databaseURL: 'https://meeting-module-4959e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'meeting-module-4959e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7vM1fQW0ZWMxE7v-xMEGf9LgBdx99xPo',
    appId: '1:808372705014:ios:69c9ac8b79b876d8c1bed7',
    messagingSenderId: '808372705014',
    projectId: 'meeting-module-4959e',
    databaseURL: 'https://meeting-module-4959e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'meeting-module-4959e.appspot.com',
    iosClientId: '808372705014-mrgne7j6bqpfrbruoumlf7bn79jevhmq.apps.googleusercontent.com',
    iosBundleId: 'com.downtownengineers.meetingModule2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7vM1fQW0ZWMxE7v-xMEGf9LgBdx99xPo',
    appId: '1:808372705014:ios:69c9ac8b79b876d8c1bed7',
    messagingSenderId: '808372705014',
    projectId: 'meeting-module-4959e',
    databaseURL: 'https://meeting-module-4959e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'meeting-module-4959e.appspot.com',
    iosClientId: '808372705014-mrgne7j6bqpfrbruoumlf7bn79jevhmq.apps.googleusercontent.com',
    iosBundleId: 'com.downtownengineers.meetingModule2',
  );
}
